<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType) {
    switch ($_attributeType){
        case 'text':
            $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
                ? $_product->getAttributeText($_code)
                : '';
            break;
        case 'image':
            if ($mId = $_product->getData('manufacturer_id')){
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $model = $objectManager->create('WS\Manufacturer\Model\Manufacturer')->load($mId);
                $src = $model->getData('image');
                if (!empty($src)){
                    $_attributeValue = $objectManager
                        ->get('Magento\Store\Model\StoreManagerInterface')
                        ->getStore()
                        ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
                    $_attributeValue .= $src;
                    $alt = $model->getData('name');
                    $_attributeValue = "<img src='$_attributeValue' alt='$alt' />";
                }
            }else{
                $_attributeValue = '';
            }

            break;
    }
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
123
    <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
        <?php if ($renderLabel) :?>
            <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
        <?php endif; ?>
        <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
    </div>
<?php endif; ?>
